### ISSUE TITLE
Fédération de contenu

### ISSUE THREAD

**Issue by alexisben** [osunyorg/theme#1032]
Gestion des redirections : 

# Piste 1 🚫

Utiliser une clé ```redirect_url``` dans le static, et gérer la redirection avec une ```meta``` dans le ```head```

```
{{ with .Params.redirect_url }}
  <meta http-equiv="refresh" content="0; url={{ . }}"/>
{{ end }}
```
 
> Solution bricolée, côté utilisateur on voit la redirection, et c'est bien moins efficace qu'une redirection 308.

# Piste 2 🚫

Modifier le permalink d'un objet : mais hugo ne supporte que les liens relatifs. 

===

# Piste 3 ✅

Ajouter une clé avec les informations du contenu fédéré

## Contenu fichier statique

```
federation:
  active: true
  canonical_url: https://osuny-demo.netlify.app/agenda/2025/event-sans-timeslot/
  website:
    name: >-
      Site de démo
    url: "https://osuny-demo.netlify.app"    
  hugo:
    permalink: "/agenda/2025/event-sans-timeslot/"
    path: "/events/2025/06/02-event-sans-timeslot"
    file: "content/fr/events/2025/06/02-event-sans-timeslot.html"
    slug: "event-sans-timeslot"
```
