### ISSUE TITLE
Pourquoi il n'y a pas d'image par défaut dans les events ?

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#557]
```
  events:
    index:
      options:
        dates: true
        categories: false
        image: false
        status: false
        subtitle: false
        summary: true
```

Je pense qu'il faudrait ça :
```
  events:
    index:
      options:
        dates: true
        categories: false
        image: true
        status: false
        subtitle: true
        summary: true
```
@Olivia206 ?
