### ISSUE TITLE
Bloc de titres

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#660]
⚠️ Besoin pour l'IUT de Bordeaux et pour Rennes

On enlève les headings, remplacés par des blocs titres :

```
  - kind: block
    template: title
    title: >-
      Un bloc de titre c'est super
    ranks:
      self: 2
    data:
      layout: classic
```

**2 layouts :** 

<img width="563" alt="Capture d’écran 2024-10-11 à 12 18 54" src="https://github.com/user-attachments/assets/ca77bd63-a384-4fde-b7fb-5270fdd11bde">
<img width="625" alt="Capture d’écran 2024-10-11 à 12 19 09" src="https://github.com/user-attachments/assets/29507766-f7b9-4313-8fa5-bba5fd3273cd">
