### ISSUE TITLE
Cas bizarre avec le bloc contact

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#703]
<img width="1792" alt="Capture d’écran 2024-10-26 à 11 04 28" src="https://github.com/user-attachments/assets/c5c714f3-a54d-47f8-aca8-0612e0f2e31a">

```yaml


  - kind: block
    template: contact
    title: >-
      
    slug: >-
      
    ranks:
      self: false
    data:
      description: >-
        

      name: >-
        Julie Grabot

      information: >-
        <p>Ingénieur de formation, ayant travaillé 10 ans dans le secteur conventionnel du bâtiment, je souhaite maintenant participer activement à la démocratisation des méthodes d'éco-construction chez les particuliers et sur les petits chantiers professionnels (moins de 800 000€HT).</p><p>Une bonne définition du cahier des charges et une bonne préparation de chantier AVANT démarrage des travaux me permettent de vous assurer une période de travaux sereine où nous minimiserons les décalages de planning et les dépassements de budget.</p>

      address:
        address: >-
          

        zipcode: >-
          

        city: >-
          

        country: >-
          

      contact_details:
        phone_numbers:
          - label: >-
              06 23 53 00 20
            value: >-
              tel:0623530020
        emails:
          - label: >-
              travauxeco33@gmail.com
            value: >-
              mailto:travauxeco33@gmail.com
        social_networks:
      phone_numbers: ["06 23 53 00 20"]

      url: >-
        

      emails: ["travauxeco33@gmail.com"]

      socials:
      timetable:
```

**Comment by arnaudlevy** [comment]
J'ai ajouté le cas et annoté

**Comment by Olivia206** [comment]
@arnaudlevy il faudrait ajouter l'adresse dans les contact_details du bloc contact s'il te plaît, pour être identique aux champs des personnes/orga/campus (je ne sais pas pour les personnes ?)

**Comment by arnaudlevy** [comment]
@Olivia206 qu'est-ce que tu penses de : 
```yaml
contact_details:
  postal_address:
    data:
      address: >-
        5 rue Frédéric Joliot Curie
      address_additional: >-
        
      zipcode: >-
        33150
      city: >-
        Cenon
      country: >-
        France
    text: >-
      5 rue Frédéric Joliot Curie 33150 Cenon FRANCE
    html: >-
      <p>5 rue Frédéric Joliot Curie<br>33150 Cenon<br>FRANCE</p>
```

J'ai harmonisé avec les personnes et les organisations

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/pull/2370

**Comment by Olivia206** [comment]
Pour text/html ça pose un souci : on ne pourra pas mettre le schema associé (ex: `<span itemprop="addressLocality">Cenon</span>`, sauf si tu veux nous l'envoyer dans le html ?

**Comment by arnaudlevy** [comment]
@Olivia206 que penses-tu de ça ? 
On peut gérer les sauts de ligne en s'appuyant sur les itemprop ?

```yaml
contact_details:
  postal_address:
    data:
      address: >-
        5 rue Frédéric Joliot Curie
      address_additional: >-
        
      zipcode: >-
        33150
      city: >-
        Cenon
      country: >-
        name: >-
          France
        alpha2: >-
          FR
        alpha3: >-
          FRA
      country: >-
        France
    text: >-
      5 rue Frédéric Joliot Curie 33150 Cenon FRANCE
    html: >-
      <address itemprop="address" itemscope itemtype="https://schema.org/PostalAddress"> <span itemprop="streetAddress">5 rue Frédéric Joliot Curie</span> <span itemprop="postalCode">33150</span> <span itemprop="addressLocality">Cenon</span> <span itemprop="addressCountry">FRANCE</span></address>
```
