### ISSUE TITLE
heure des événements étrange

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#729]
![Capture d’écran 2024-11-14 à 16 45 17](https://github.com/user-attachments/assets/65f3c0e5-9c0b-4714-9c7d-20a9208bf986)

**Comment by arnaudlevy** [comment]
Trop bizarre. La data ressemble à quoi si tu l'as pas loin ?

**Comment by Olivia206** [comment]
```
date: "2024-06-12"
dates:
  status: "archive"
  archive: true
  computed:
    short: >-
      June 12, 2024
    long: >-
      Wednesday June 12, 2024
    two_lines:
      short: >-
        June 12, 2024
      long: >-
        Wednesday June 12, 2024
  from:
    day: 2024-06-12
    hour: 15:00
  to:
    day: 2024-06-12
    hour: 17:00
    ```
    
    
   (ça c'est cids mais même souci)
   je crois que c'est côté css, avec le grid-column qui fait un peu n'importe quoi
