### ISSUE TITLE
Où sont les options de pages ?

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#835]
J'ai essayé ça mais ça ne fait rien du tout 
```yaml
  pages:
    index:
      options:
        summary: false
```

Je voulais enlever les résumés dans le layout grid par défaut appliqué aux pages enfants 
https://site.frenchcraftguild.osuny.site/a-propos/
<img width="1784" alt="Capture d’écran 2024-12-20 à 07 53 00" src="https://github.com/user-attachments/assets/4034b2f9-a563-4e2c-8728-7d9d5afee17f" />
