### ISSUE TITLE
Créer des fichiers de configuration par type d'objets

### ISSUE THREAD

**Issue by alexisben** [osunyorg/theme#950]
Le fichier de config hugo.yaml fait 700 lignes. Il devient difficile de naviguer et de s'y retrouver à l'intérieur. Il serait intéressant d'utiliser des fichiers de data :

```
section:
  layout:
  options:
  truncate:
single:
  layout:
  options:
  truncate:
image_sizes:
  section:
  single:
  layouts:
    list:
    grid:
    cards:
```

```
taxonomy:
  layout:
  options:
  truncate:
term:
  layout:
  options:
  truncate:
image_sizes:
  section:
  single:
  layouts:
    list:
    grid:
    cards:

```
